### PR TITLE
add file url link to update alert message

### PR DESCRIPTION
**Pull request by ROMVoid95**
Notes: Not a direct download
example: https://www.curseforge.com/minecraft/modpacks/galacticsurvival/files/2845352

### CODE REVIEW

**Comment by TheRandomLabs** [comment]
You can now directly call `CurseFile#url()`. :)

**Comment by ROMVoid95** [comment]
i know! lol i wish i had seen that prior to making this edit lol the project made HUGE changes since the last time i looked at it.

**Comment by TheRandomLabs** [comment]
The rewrite is still WIP. :P

**Comment by ROMVoid95** [comment]
if your ever in need of some help i'm willing to help out. built quite a few bots for discord and this one peeks an interest in me lol rock on

**Pull request merged**
